# 日志打印级别
logging:
  level:
    com.example.messagegateway: INFO
    io.swagger.models.parameters.AbstractSerializableParameter: error
# mysql   ${mysql.url}  ${mysql.username}  ${mysql.password}47.95.252.189
mysql:
  url: jdbc:mysql://127.0.0.1:3306/message_gateway?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
  username: root
  password: root

